name: Check PR can be merged
on: 
  pull_request:
    types: [labeled]
    branches:
      - develop/*       # The branch you want to automatically merge pull request
jobs:
  Run Actions:
    runs-on: [ubuntu-latest]
    steps:
    - name: Automatically Merge PR
      uses: plm9606/automerge_actions@1.0.0
      with:
        # The PR label name you want to use when merge PR automatically.
        label-name: # If you don't write it, default is automerge
        # GitHub WebHook Secret Token
        github-token: ${{ secrets.TOKEN }}
